export const QUERY_KEYS = {
  comforts: "comforts",
  cottages: "cottages",
  cottagetypes: "cottagetypes",
  users: "users",
  languages: "languages",
  regions: "regions",
  places: "places",
  notifications: "notifications",
  roles: "roles",
  translates: "translates",
  services: "services",
  tariff: "tariff",
  unusedTranslates: "unusedTranslates",
  models: "models",
};
